# Understanding `torch.nn.Linear` in PyTorch

- `torch.nn.Linear` is a module that applies a linear transformation to the incoming data:
    - `Y = X A^T + b`.

## Linear layer with auto generated parameters

In [1]:
import torch
import torch.nn as nn

# nn.Linear(in_features, # number of input features
#           out_features,# number of output features
#           bias)        # whether to add a bias term

# Linear layer with auto generated parameters #####################################
print("# Linear layer with auto generated parameters:")

# Create a linear layer with 3 input features and 2 output features
linear_layer_auto_gen = nn.Linear(in_features=3, out_features=2)
print(linear_layer_auto_gen)

for name, param in linear_layer_auto_gen.named_parameters():
    print("---------")
    print(f"{name}: {param.shape}")
    print(param)
    print("---------")
###################################################################################

print("\n")
input = torch.tensor([[1.0, 2.0, 3.0]])
output = linear_layer_auto_gen(input)
print(output)


# Linear layer with auto generated parameters:
Linear(in_features=3, out_features=2, bias=True)
---------
weight: torch.Size([2, 3])
Parameter containing:
tensor([[ 0.0737, -0.1006,  0.1175],
        [ 0.2915,  0.2551, -0.0987]], requires_grad=True)
---------
---------
bias: torch.Size([2])
Parameter containing:
tensor([-0.2243,  0.0985], requires_grad=True)
---------


tensor([[0.0006, 0.6041]], grad_fn=<AddmmBackward0>)


## Linear layer with specified parameters

In [2]:
import torch
import torch.nn as nn

# nn.Linear(in_features, # number of input features
#           out_features,# number of output features
#           bias)        # whether to add a bias term

# Linear layer with specified parameters ##########################################
print("# Linear layer with specified parameters:")

# Create a linear layer with 3 input features and 2 output features
linear_layer= nn.Linear(in_features=3, out_features=2)
# Specify the weight and bias
# Weight: 
# [[1.0, 2.0, 3.0], 
#  [4.0, 5.0, 6.0]]
linear_layer.weight = nn.Parameter(torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]))
# Bias: [1.0, 2.0]
linear_layer.bias = nn.Parameter(torch.tensor([1.0, 2.0]))
print(linear_layer)

for name, param in linear_layer.named_parameters():
    print("---------")
    print(f"{name}: {param.shape}")
    print(param)
    print("---------")
###################################################################################

print("\n")
input = torch.tensor([[1.0, 2.0, 3.0]])
output = linear_layer(input)
print(output)
# Handwrite the calculations:
# [[1., 2., 3.],
#  [4., 5., 6.]] * [1.0, 2.0, 3.0] + [1.0, 2.0]


# Linear layer with specified parameters:
Linear(in_features=3, out_features=2, bias=True)
---------
weight: torch.Size([2, 3])
Parameter containing:
tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
---------
---------
bias: torch.Size([2])
Parameter containing:
tensor([1., 2.], requires_grad=True)
---------


tensor([[15., 34.]], grad_fn=<AddmmBackward0>)
